routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes([
    'reset' => false,
    'verify' => false,
]);

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('employee/{employee}', [EmployeeController::class, 'show'])->name('employee');

Route::prefix('admin')->name('admin.')->middleware('role:admin')->group(function () {
    Route::redirect('/', 'admin/employee')->name('dashboard');
    Route::resource('employee', 'Admin\EmployeeController');
    Route::resource('position', 'Admin\PositionController');
    Route::resource('skill', 'Admin\SkillController');
});

resources/views/admin/admin.blade.php
@extends('layouts/app')

@section('content')
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <ul class="nav nav-pills nav-stacked">
                        <li @if (request()->is('admin/employee*')) class="active" @endif>
                            <a href="{{ route('admin.employee.index') }}">Сотрудники</a>
                        </li>
                        <li @if (request()->is('admin/position*')) class="active" @endif>
                            <a href="{{ route('admin.position.index') }}">Должности</a>
                        </li>
                        <li @if (request()->is('admin/skill*')) class="active" @endif>
                            <a href="{{ route('admin.skill.index') }}">Навыки</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            @yield('columncontent')
        </div>
    </div>
@endsection