routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes([
    'reset' => false,
    'verify' => false,
]);

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('employee/{employee}', [EmployeeController::class, 'show'])->name('employee');

Route::prefix('admin')->name('admin.')->middleware('role:admin')->group(function () {
    Route::redirect('/', 'admin/employee')->name('dashboard');
    Route::resource('employee', 'Admin\EmployeeController');
    Route::resource('position', 'Admin\PositionController');
    Route::resource('skill', 'Admin\SkillController');
});

app/Models/Employee.php
<?php

namespace App\Models;

use App\Traits\Dtoable;
use App\Traits\Filter\EmployeeFilter;
use App\Traits\Sortable;
use App\Traits\Filterable;
use App\Traits\Search\EmployeeSearch;
use App\Traits\Sort\EmployeeSort;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

/**
 * Сотрудник
 *
 * @property int $id
 * @property Carbon $created_at
 * @property Carbon $update_at
 * @property int $user_id
 * @property string $fio
 * @property string $email
 * @property string $phone
 * @property int $positon_id
 */
class Employee extends BaseModel
{
    use Dtoable,
        Sortable,
        Filterable,
        EmployeeSort,
        EmployeeFilter,
        EmployeeSearch;

    protected $table = 'employees';

    protected $fillable = [
        'fio',
        'email',
        'phone',
        'position_id',
    ];

    /**
     * ID навыков
     *
     * @return array
     */
    public function getSkillIdsAttribute(): array
    {
        return $this->skills()->pluck('id')->toArray();
    }

    /**
     * Должность
     *
     * @return BelongsTo
     */
    public function position(): BelongsTo
    {
        return $this->belongsTo(Position::class);
    }

    /**
     * Навыки
     *
     * @return BelongsToMany
     */
    public function skills(): BelongsToMany
    {
        return $this->belongsToMany(Skill::class);
    }

    /**
     * Пользователь
     *
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admin/EmployeeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Dto\ModelDTO;
use App\Http\Controllers\Controller;
use App\Http\Requests\EmployeeRequest;
use App\Models\Employee;
use App\Models\Position;
use App\Models\Skill;
use App\Services\EmployeeService;
use Spatie\Permission\Models\Role;

class EmployeeController extends Controller
{
    private EmployeeService $employeeService;

    public function __construct(EmployeeService $employeeService)
    {
        $this->employeeService = $employeeService;
    }

    public function index(ModelDTO $dto)
    {
        $employees = Employee::query()
            ->with(['position', 'skills'])
            ->collection($dto);
        $templateData = [
            'employees' => $employees,
        ];
        return view('admin/employee/index', $templateData);
    }

    public function edit(Employee $employee)
    {
        $employee->setAppends(['skill_ids']);
        $positions = Position::pluck('name', 'id');
        $skills = Skill::pluck('name', 'id');
        $roles = Role::pluck('name', 'id');
        $templateData = [
            'employee' => $employee,
            'positions' => $positions,
            'skills' => $skills,
            'roles' => $roles,
        ];
        return view('admin/employee/form', $templateData);
    }

    public function update(Employee $employee, EmployeeRequest $request)
    {
        $this->employeeService->update($employee, $request->all());
        return redirect()->route('admin.employee.index')->withMessage('Обновлено');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;

class EmployeeController extends Controller
{
    public function show(Employee $employee)
    {
        $templateData = [
            'employee' => $employee,
        ];
        return view('employee', $templateData);
    }
}

resources/views/admin/employee/form.blade.php
@extends('admin/admin')

@section('columncontent')
    @include('components/error')
    <form action="{{ route('admin.employee.update', ['employee' => $employee]) }}" method="post">
        @csrf
        @method('put')
        <div class="form-group">
            <label for="fio">ФИО</label>
            <input name="fio" type="text" class="form-control" value="{{ old('fio') ?? $employee->fio ?? '' }}" autofocus required>
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input name="email" type="text" class="form-control" value="{{ old('email') ?? $employee->email ?? '' }}" autofocus required>
        </div>
        <div class="form-group">
            <label for="phone">Телефон</label>
            <input name="phone" type="text" class="form-control" value="{{ old('phone') ?? $employee->phone ?? '' }}" autofocus required>
        </div>
        <div class="form-group">
            <label for="position">Должность</label>
            <select name="position_id" id="position" class="form-control">
                @foreach ($positions as $positionId => $positionName)
                    <option value="{{ $positionId }}" @if ($positionId == (old('position_id') ?? $employee->position->id ?? null)) selected @endif>{{ $positionName }}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="skill">Навыки</label>
            <div class="row">
                @foreach ($skills as $skillId => $skillName)
                    <div class="col-md-2">
                        <input type="checkbox" name="skill_ids[]" value="{{ $skillId }}" @if (in_array($skillId, (old('skill_ids') ?? $employee->skill_ids))) checked @endif> {{ $skillName }}
                    </div>
                @endforeach
            </div>
        </div>
        <div class="form-group">
            <label for="role">Роль</label>
            <select name="role_id" id="role" class="form-control">
                @foreach ($roles as $roleId => $roleName)
                    <option value="{{ $roleId }}" @if (old('role_id') ? $roleId == old('role_id') : $employee->user->hasRole($roleName)) selected @endif>{{ $roleName }}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
    </form>
@endsection

resources/views/admin/employee/index.blade.php
@extends('admin/admin')

@section('columncontent')
    <table class="table table-condensed table-hover">
        <thead>
            <tr>
                <th>ФИО</th>
                <th>Email</th>
                <th>Телефон</th>
                <th>Должность</th>
                <th>Навыки</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach ($employees as $employee)
                <tr>
                    <td>{{ $employee->fio }}</td>
                    <td>{{ $employee->email }}</td>
                    <td>{{ $employee->phone }}</td>
                    <td>{{ $employee->position->name ?? '' }}</td>
                    <td>
                        <ul>
                            @foreach ($employee->skills as $skill)
                                <li>{{ $skill->name }}</li>
                            @endforeach
                        </ul>
                    </td>
                    <td>
                        <a href="{{ route('admin.employee.edit', ['employee' => $employee]) }}" class="btn btn-primary">Редактировать</a>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    {{ $employees->links() ?? '' }}
@endsection