routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes([
    'reset' => false,
    'verify' => false,
]);

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('employee/{employee}', [EmployeeController::class, 'show'])->name('employee');

Route::prefix('admin')->name('admin.')->middleware('role:admin')->group(function () {
    Route::redirect('/', 'admin/employee')->name('dashboard');
    Route::resource('employee', 'Admin\EmployeeController');
    Route::resource('position', 'Admin\PositionController');
    Route::resource('skill', 'Admin\SkillController');
});

app/Models/Position.php
<?php

namespace App\Models;

use App\Traits\Dtoable;
use App\Traits\Filterable;
use App\Traits\Sortable;

/**
 * Должность
 *
 * @property int $id
 * @property Carbon $created_at
 * @property Carbon $updated_at
 * @property string $name
 */
class Position extends BaseModel
{
    use Dtoable,
        Sortable,
        Filterable;

    protected $table = 'positions';

    protected $fillable = [
        'name',
    ];
}

app/Http/Controllers/Admin/PositionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Dto\ModelDTO;
use App\Http\Controllers\Controller;
use App\Http\Requests\PositionRequest;
use App\Models\Position;
use App\Services\PositionService;

class PositionController extends Controller
{
    private PositionService $positionService;

    public function __construct(PositionService $positionService)
    {
        $this->positionService = $positionService;
    }

    public function index(ModelDTO $dto)
    {
        $positions = Position::query()->collection($dto);
        $templateData = [
            'positions' => $positions
        ];
        return view('admin/position/index', $templateData);
    }

    public function create()
    {
        return view('admin/position/form');
    }

    public function store(PositionRequest $request)
    {
        $this->positionService->create($request->only('name'));
        return redirect()->route('admin.position.index')->withMessage('Создано');
    }

    public function edit(Position $position)
    {
        $templateData = [
            'position' => $position,
        ];
        return view('admin/position/form', $templateData);
    }

    public function update(Position $position, PositionRequest $request)
    {
        $this->positionService->update($position, $request->only('name'));
        return redirect()->route('admin.position.index')->withMessage('Обновлено');
    }

    public function destroy(Position $position)
    {
        $this->positionService->remove($position);
        return redirect()->route('admin.position.index')->withMessage('Удалено');
    }
}

resources/views/admin/position/form.blade.php
@extends('admin/admin')

@section('columncontent')
    @include('components/error')
    <form action="{{ isset($position) ? route('admin.position.update', ['position' => $position]) : route('admin.position.store') }}" method="post">
        @csrf
        @method(isset($position) ? 'put' : 'post')
        <div class="form-group">
            <label for="name">Наименование</label>
            <input name="name" type="text" class="form-control" value="{{ old('name') ?? $position->name ?? '' }}" autofocus required>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
    </form>
@endsection

resources/views/admin/position/index.blade.php
@extends('admin/admin')

@section('columncontent')
    <div class="row">
        <div class="col-md-2">
            <a href="{{ route('admin.position.create') }}" class="btn btn-primary">Создать</a>
        </div>
    </div>
    <br>
    @include('components/message')
    <table class="table table-condensed table-hover">
        <thead>
            <tr>
                <th>Наименование</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach ($positions as $position)
                <tr>
                    <td>{{ $position->name }}</td>
                    <td>
                        <a href="{{ route('admin.position.edit', ['position' => $position]) }}" class="btn btn-primary">Редактировать</a>
                        <button class="btn btn-danger" onclick="deleteModel('position', {{ $position->id }})">Удалить</button>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    {{ $positions->links() ?? '' }}
@endsection