routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes([
    'reset' => false,
    'verify' => false,
]);

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('employee/{employee}', [EmployeeController::class, 'show'])->name('employee');

Route::prefix('admin')->name('admin.')->middleware('role:admin')->group(function () {
    Route::redirect('/', 'admin/employee')->name('dashboard');
    Route::resource('employee', 'Admin\EmployeeController');
    Route::resource('position', 'Admin\PositionController');
    Route::resource('skill', 'Admin\SkillController');
});

app/Models/Skill.php
<?php

namespace App\Models;

use App\Traits\Dtoable;
use App\Traits\Filterable;
use App\Traits\Sortable;

/**
 * Навык
 *
 * @property int $id
 * @property Carbon $created_at
 * @property Carbon $updated_at
 * @property string $name
 */
class Skill extends BaseModel
{
    use Dtoable,
        Sortable,
        Filterable;

    protected $table = 'skills';

    protected $fillable = [
        'name',
    ];
}

app/Http/Controllers/Admin/SkillController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Dto\ModelDTO;
use App\Http\Controllers\Controller;
use App\Http\Requests\SkillRequest;
use App\Models\Skill;
use App\Services\SkillService;

class SkillController extends Controller
{
    private SkillService $skillService;

    public function __construct(SkillService $skillService)
    {
        $this->skillService = $skillService;
    }

    public function index(ModelDTO $dto)
    {
        $skills = Skill::query()->collection($dto);
        $templateData = [
            'skills' => $skills
        ];
        return view('admin/skill/index', $templateData);
    }

    public function create()
    {
        return view('admin/skill/form');
    }

    public function store(SkillRequest $request)
    {
        $this->skillService->create($request->only('name'));
        return redirect()->route('admin.skill.index')->withMessage('Создано');
    }

    public function edit(Skill $skill)
    {
        $templateData = [
            'skill' => $skill,
        ];
        return view('admin/skill/form', $templateData);
    }

    public function update(Skill $skill, SkillRequest $request)
    {
        $this->skillService->update($skill, $request->only('name'));
        return redirect()->route('admin.skill.index')->withMessage('Обновлено');
    }

    public function destroy(Skill $skill)
    {
        $this->skillService->remove($skill);
        return redirect()->route('admin.skill.index')->withMessage('Удалено');
    }
}

resources/views/admin/skill/form.blade.php
@extends('admin/admin')

@section('columncontent')
    @include('components/error')
    <form action="{{ isset($skill) ? route('admin.skill.update', ['skill' => $skill]) : route('admin.skill.store') }}" method="post">
        @csrf
        @method(isset($skill) ? 'put' : 'post')
        <div class="form-group">
            <label for="name">Наименование</label>
            <input name="name" type="text" class="form-control" value="{{ old('name') ?? $skill->name ?? '' }}" autofocus required>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
    </form>
@endsection

resources/views/admin/skill/index.blade.php
@extends('admin/admin')

@section('columncontent')
    <div class="row">
        <div class="col-md-2">
            <a href="{{ route('admin.skill.create') }}" class="btn btn-primary">Создать</a>
        </div>
    </div>
    <br>
    @include('components/message')
    <table class="table table-condensed table-hover">
        <thead>
            <tr>
                <th>Наименование</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach ($skills as $skill)
                <tr>
                    <td>{{ $skill->name }}</td>
                    <td>
                        <a href="{{ route('admin.skill.edit', ['skill' => $skill]) }}" class="btn btn-primary">Редактировать</a>
                        <button class="btn btn-danger" onclick="deleteModel('skill', {{ $skill->id }})">Удалить</button>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    {{ $skills->links() ?? '' }}
@endsection